
// user
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGOUT = "LOGOUT";
// contact
export const CONTACTS_SUCCESS= "CONTACTS_SUCCESS";
export const CONTACTS_ERROR = "CONTACTS_ERROR";
export const CONTACTS_ATTEMPT = "CONTACTS_ATTEMPT";
// register
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ATTEMPT = "REGISTER_ATTEMPT";
